server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /tasks {
        proxy_pass http://app:8080;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Content-Type $http_content_type;
        proxy_set_header Host $host;
    }
}
